= Effect Box

EffectBox is a widget for Unreal Engine that allows applying custom materials.
For example, to make curved HUD, implement UI shake or apply other post-effects.

[[usage]]
== How to use

. Create a material with "User Interface" domain and "Alpha Composite (Premultiplied Alpha)" blend mode
. Add `EffectBox` to your UMG widget
. Specify your material in "Effect Material" widget field
. Specify texture parameter name in "Texture Parameter" widget field
. You're done!

[[example]]
== Example

.Minimal material
image:https://github.com/user-attachments/assets/3415054c-4c85-46c7-8604-956fefa00ef2[width=640]

.Example Widget
image:https://github.com/user-attachments/assets/f11dd6cc-a20c-4894-b3f2-c9d6f178b61e[width=640]

[[retainerbox]]
== What's wrong with RetainerBox?

* RetainerBox doesn't play well with https://dev.epicgames.com/documentation/en-us/unreal-engine/invalidation-in-slate-and-umg-for-unreal-engine[Slate Global Invalidation].
It invalidates too much aggressively, resulting in bad performance.
With complex UIs, EffectBox is able to save up to multiple milliseconds compared to RetainerBox.
* RetainerBox had long-standing bugs (https://issues.unrealengine.com/issue/UE-107863[UE-107863], https://issues.unrealengine.com/issue/UE-114934[UE-114934], https://issues.unrealengine.com/issue/UE-203471[UE-203471] and so on) that only got fixed in Unreal Engine 5.4.
* RetainerBox is _very_ complex.
Its primary goal is to reduce UI redraw rate, which it implements by caching UI in a render target.
Actually, that could even be achieved without introducing a render target, so it is questionable whether RetainerBox solves its task _effectively_.
When one uses RetainerBox to draw each frame just to apply visual effects, it is just an ineffective overkill.
